// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: api/protobuf-spec/frontend.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api {

  /// <summary>Holder for reflection information generated from api/protobuf-spec/frontend.proto</summary>
  public static partial class FrontendReflection {

    #region Descriptor
    /// <summary>File descriptor for api/protobuf-spec/frontend.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FrontendReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBhcGkvcHJvdG9idWYtc3BlYy9mcm9udGVuZC5wcm90bxIDYXBpGiBhcGkv",
            "cHJvdG9idWYtc3BlYy9tZXNzYWdlcy5wcm90bzKsAQoIRnJvbnRlbmQSNAoM",
            "Q3JlYXRlUGxheWVyEhAubWVzc2FnZXMuUGxheWVyGhAubWVzc2FnZXMuUmVz",
            "dWx0IgASNAoMRGVsZXRlUGxheWVyEhAubWVzc2FnZXMuUGxheWVyGhAubWVz",
            "c2FnZXMuUmVzdWx0IgASNAoKR2V0VXBkYXRlcxIQLm1lc3NhZ2VzLlBsYXll",
            "choQLm1lc3NhZ2VzLlBsYXllciIAMAFCN1o1Z2l0aHViLmNvbS9Hb29nbGVD",
            "bG91ZFBsYXRmb3JtL29wZW4tbWF0Y2gvaW50ZXJuYWwvcGJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Messages.MessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
